// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYeJhfP93HMgEea4q_dSAyXqJUgwVkjUQ',
    appId: '1:284119484102:web:5d5d7c28dafdf71f2af9c7',
    messagingSenderId: '284119484102',
    projectId: 'cimaparkv2',
    authDomain: 'cimaparkv2.firebaseapp.com',
    storageBucket: 'cimaparkv2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFOYFvtFKLVCdu1T5VJDurWxfnGZS4veI',
    appId: '1:284119484102:android:9fb7172648040b902af9c7',
    messagingSenderId: '284119484102',
    projectId: 'cimaparkv2',
    storageBucket: 'cimaparkv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGLdk84Y8n55cyrtpG2RMoQHLyJUTQ_c0',
    appId: '1:284119484102:ios:8d50bd3bdfb2b8142af9c7',
    messagingSenderId: '284119484102',
    projectId: 'cimaparkv2',
    storageBucket: 'cimaparkv2.firebasestorage.app',
    iosBundleId: 'com.example.cimaparkv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGLdk84Y8n55cyrtpG2RMoQHLyJUTQ_c0',
    appId: '1:284119484102:ios:8d50bd3bdfb2b8142af9c7',
    messagingSenderId: '284119484102',
    projectId: 'cimaparkv2',
    storageBucket: 'cimaparkv2.firebasestorage.app',
    iosBundleId: 'com.example.cimaparkv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYeJhfP93HMgEea4q_dSAyXqJUgwVkjUQ',
    appId: '1:284119484102:web:a5952556b9f1d4662af9c7',
    messagingSenderId: '284119484102',
    projectId: 'cimaparkv2',
    authDomain: 'cimaparkv2.firebaseapp.com',
    storageBucket: 'cimaparkv2.firebasestorage.app',
  );
}
